import Home from "./views/pages/Home"
import Cart  from "./views/components/Cart"
import Itemframes from "./views/components/Itemframes"
import Customers from "./views/components/Customers"
import CustomersService from "./views/pages/CustomersService"
import CustomerDetail from "./views/pages/CustomerDetail"
import MyAccount from "./views/pages/MyAccount"
import Orders from "./views/pages/Orders"
import Navbar from "./views/components/Navbar"
import LoadingSpinner from "./views/components/LoadingSpinner"
import Skelleton from "./views/components/Skelleton"
import FavoriteItems from "./views/components/FavoriteItems"
import Login from "./views/pages/Login"
import Register from "./views/pages/Register"
export {Home,Navbar,Orders,Cart,Itemframes,Customers,LoadingSpinner,Skelleton,FavoriteItems,Login,Register,CustomersService,CustomerDetail,MyAccount}